// <auto-generated />
using EmployeeCRUD_MVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeCRUD_MVC.Migrations
{
    [DbContext(typeof(EmployeeDBContext))]
    [Migration("20211028004740_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EmployeeCRUD_MVC.Models.Department", b =>
                {
                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentName");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EmployeeCRUD_MVC.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentsDepartmentName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentsDepartmentName");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeCRUD_MVC.Models.Employee", b =>
                {
                    b.HasOne("EmployeeCRUD_MVC.Models.Department", "Departments")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentsDepartmentName");

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("EmployeeCRUD_MVC.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
